# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gunn1

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: "echo '  CONTAINER: appengine' >> app.yaml"
    - run: "echo '  RHOST: ${{ secrets.RHOST }}' >> app.yaml"
    - run: "echo '  schoology_key: ${{ secrets.schoology_key }}' >> app.yaml"
    - run: "echo '  schoology_secret: ${{ secrets.schoology_secret }}' >> app.yaml"
    - run: "echo '  schoology_secret: ${{ secrets.schoology_secret }}' >> app.yaml"
    - run: "echo '  MONGO_URL: ${{ secrets.MONGO_URL }}' >> app.yaml"
    - run: "echo '  cookie_secret: ${{ secrets.cookie_secret }}' >> app.yaml"
    - id: Deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
